### PR TITLE
Fixed robot file placement I think

### PR DESCRIPTION
**Pull request by cheesebroccoli**
Honestly github continues to be an enigma that escapes me at every turn

### CODE REVIEW

**Comment by torinriley** [comment]
you need to fix the merge conflicts

**Comment by cheesebroccoli** [comment]
Why cant you

**Comment by torinriley** [comment]
because idk what changes and stuff you have on you're branch, just do this

```bash
git pull origin master
```

```bash
git checkout Chen-Chen
```

```bash
git merge master
```

then follow the instructions it gives you in the terminal, you can also look at this, 
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line

**Comment by cheesebroccoli** [comment]
):

**Comment by torinriley** [comment]
you could just forget your branch, make a new one, from the main branch, and then change the moter references, then no conflicts!

**Pull request merged**
